### ISSUE TITLE
No response for a presence of QR code

### ISSUE THREAD

**Issue by nozomi328** [ericksli/play-safe#1]
Hello,

Please see attachments. Thank you.

Regards.

![Screenshot_20201128-181831](https://user-images.githubusercontent.com/75163374/100503125-15cd2f00-31a7-11eb-9cae-1853f2291cde.png)
![Screenshot_20201128-182508](https://user-images.githubusercontent.com/75163374/100503192-1a91e300-31a7-11eb-8acb-e4a66c539d7d.png)

**Comment by ericksli** [comment]
I also encounter same or similar issue on OnePlus 3T (OnePlus ONEPLUS A3003). It cannot detect any QR code. (The ML Kit barcode scanner result only return empty array even the camera is shooting at a QR code)

I also tried with [ScannerX](https://github.com/maulikhirani/scannerX) project, no matter using ML Kit or ZXing library it still cannot detect any QR code on OnePlus 3T. Looks like a bug in CameraX library.

**Comment by ericksli** [comment]
@infilmity 應該係 CameraX 問題，正話 update 咗 dependency version，麻煩再試試，試完通知返得唔得。

@nozomi328 Please try with the latest release v1.1.1. I have updated the dependencies and tried with OnePlus 3T and works now (previously could not work.)

**Comment by nozomi328** [comment]
![Screenshot_20210104-230059](https://user-images.githubusercontent.com/75163374/103548493-d8b03700-4ee0-11eb-9a30-48d2cd1e9a85.png)

Test OK, thanks a lot. Will close issue after confirming @infilmity testing result.

**Comment by infilmity** [comment]
> @infilmity 應該係 CameraX 問題，正話 update 咗 dependency version，麻煩再試試，試完通知返得唔得。
> 
> @nozomi328 Please try with the latest release v1.1.1. I have updated the dependencies and tried with OnePlus 3T and works now (previously could not work.)
> 
> ![device-2021-01-04-215916](https://user-images.githubusercontent.com/709774/103543901-3ab96e00-4eda-11eb-83e3-dc50c262a665.png)

謝謝，頭先收工無拎走部手機，聽日下晝我再覆丫😌

**Comment by infilmity** [comment]
1.1.1在我兩部機都成功☺️謝謝

**Comment by nozomi328** [comment]
All users tested ok, close issue. Thanks a lot.
